### ISSUE TITLE
TODO list for V2.1.0

### ISSUE THREAD

**Issue by dani007200964** [dani007200964/Commander-API#10]
# Todo list for the next release!

- [x] Try to solve the AVR PROGMEM thing, to reduce RAM usage
- [x] Implement piping
- [ ] Documenting the new functions
- [ ] Check Shellminator compatibility
- [x] Tests with other platforms( STM32... )
- [x] OPTIONAL: Better logo and footer.
- [x] Modify it to use Stream class
- [ ] Update examples with Stream
- [ ] Modify GitHub Actions for new examples

# Premade commands:

- [x] millis
- [x] micros
- [x] uptime
- [x] neofetch
- [x] reboot
- [x] digitalRead
- [x] digitalWrite
- [x] pinMode
- [x] wifiScan
- [x] wifiStat
- [x] ipconfig
- [x] sin
- [x] cos
- [x] not
- [x] abs
- [x] random
- [x] configTime
- [x] dateTime
- [ ] i2cBegin
- [ ] i2cScanner
- [ ] i2cRead
- [ ] i2cWrite

**Comment by MrNoname3** [comment]
Commands for ESPs:
- datetime ( If someone use NTP time sync )
- sleep ( for given seconds/milliseconds, only for ESP32 )
