### ISSUE TITLE
ToDo list for new version

### ISSUE THREAD

**Issue by dani007200964** [dani007200964/Commander-API#17]
- [x] PC simulator
- [ ] Unit tests :construction: 
- [x] Enable almost all functions on any platform :construction:
- [x] Doxygen theme as submodule
- [ ] Add a function to the database class, which can check if the name is correct( doesn't have spec. characters etc.. ).
- [ ] Better configuration header :construction:
- [x] Argument parser :construction:
- [x] Create a simple solution to FF macro :construction:
- [x] Dedicate a function to Argument error text to save program memory :construction:
- [x] echo and env function
- [x] System variables and use them as arguments
- [x] System constants and use them as arguments
- [x] memDump function ( memory dump )
- [ ] regMan function ( register manipulation )
- [x] Add a simple update function to use it without any terminal interface.
- [x] Came up with a new solution for the optimizer without recursion.
- [x] Better documentation: :construction:
    - [x] More examples :construction:
    - [ ] Coverage report :construction:
    - [x] Interactive demo for each example :construction:

:construction: - means under development
